cursosflix/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

#namespace é usado para agrupar URLs sob um prefixo comum, o que é útil para evitar conflitos de nome quando você tem várias aplicações que podem ter rotas com nomes iguais.
#Basicamente ele identifica o arquivo url.py do app exato que ele precisa pegar, cujo a variável "app_name" possui o mesmo nome que foi passado como parâmetro para a variável "namespace"
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('filme.urls', namespace='filme')),
]
#urls para os arquivos estáticos
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
#urls para os arquivos de mídia
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

filme/urls.py
# url - view - template
from django.urls import path, reverse_lazy
#reverse_lazy: Passado pro path para retornar o link da página que o usuário vai entrar ao submeter o formulário
from .views import HomeFilmes, Homepage, DetalhesFilme, Pesquisafilme, EditarPerfil, CriarConta
#Importação para pegar a classe de Login que já vem pronta do Django
from django.contrib.auth import views as auth_view

#app_name é usada dentro dos arquivos urls.py de um aplicativo para definir um namespace próprio para esse conjunto de URLs.
app_name = "filme"

#Para Functions Base Views: Passar o nome da função como parâmetro o Django já vai entender que queremos renderizar a página HTML que está definida na função
#Para Class Base Views: Necessário passar NomeDaClasse.as_view() - "()" É obrigatório passar.

#A criação do link de página que renderiza uma DetailView é diferente:
#Ele espera que tenha um parâmetro na url dentro de "< >" - E também precisa informar o tipo desse parâmetro. Ex: int, float, str...
#No exemplo foi utilizado "int:pk" onde "pk" é a primary key da tabela que foi implementada na DetailView
#Ele faz essa busca automaticamente - Tendo em mente que foi definida a tabela do banco de dados que vamos renderizar
urlpatterns = [
    path('', Homepage.as_view(), name="homepage"),
    path('filmes/', HomeFilmes.as_view(), name="homefilmes"),
    path('filmes/<int:pk>', DetalhesFilme.as_view(), name="detalhesfilme"),
    path('pesquisa/', Pesquisafilme.as_view(), name="pesquisafilme"),
    #template_name: Para o Django diferenciar os HTML's das views que possuem a classe pronta do Django.
    path('login/', auth_view.LoginView.as_view(template_name="login.html"), name="login"),
    path('logout/', auth_view.LogoutView.as_view(template_name="logout.html"), name="logout"),
    path('editar-perfil/<int:pk>', EditarPerfil.as_view(), name="editarperfil"),
    path('criar-conta/', CriarConta.as_view(), name="criarconta"),
    path('alterar-senha/', auth_view.PasswordChangeView.as_view(template_name="editarperfil.html",
                                                                success_url=reverse_lazy('filme:homefilmes')), name="mudarsenha")
]

#o parâmetro name usado nas rotas (URLs) serve para dar um nome único a cada rota, permitindo que você se refira a essas rotas d    e uma maneira mais fácil e robusta em todo o seu código.

filme/models.py
from django.db import models
#Essa importação do django é para trabalhar com horas
from django.utils import timezone
#Importação para criar o modelo de usuário - Usuário padrão do Django
from django.contrib.auth.models import AbstractUser

# Create your models here.
#Categorias para a coluna "categorias" - Necessáriamente precisa ser uma tupla.
#(Primeiro parâmetro: Vai aparecer no banco de dados, Segundo parâmetro: Vai aparecer pros usuários)
LISTA_CATEGORIAS = (
    ("ANALISES", "Análises"),
    ("PROGRAMACAO", "Programação"),
    ("APRESENTACAO", "Apresentação"),
    ("OUTROS", "Outros")
)
#Criar o filme
class Filme(models.Model):
    #Cria as colunas da tabela Filme do banco de dados
    #Titulo -  models.CharField - Indica que essa coluna será do tipo string | max_lenght - Definindo a quantidade de caracteres.
    titulo = models.CharField(max_length=100)
    #Thumb - upload_to - É passado para esse parâmetro onde vão ficar armazenados as imagens dos filmes à medida que forem criados
    thumb = models.ImageField(upload_to="thumb_filmes")
    #Descricao - models.TextField - Mesma coisa que o CharField. Porém serve para textos grandes.
    descricao = models.TextField(max_length=1000)
    #choices - Parâmetro que vai armazenar a lista de categorias para o bd
    categoria = models.CharField(max_length=15, choices=LISTA_CATEGORIAS)
    views = models.IntegerField(default=0)
    data_criacao = models.DateTimeField(default=timezone.now)

    #Essa função nativa do python - Define o que vai aparecer pro usuário quando ele der um print em algum item da Classe em que ele está definido.
    def __str__(self):
        return self.titulo


#Criar os episódios
#models.ManyToManYField - Cria uma relação muitiplas entre as tabelas, ou seja, muitos p/ muitos
class Episodio(models.Model):
    #related_name - É o que de fato faz eu conseguir referenciar no código os episódios que estão relacionados a um determinado filme.
    #on_delete=models.CASCADE - Basicamente ele cria a funcionalidade de excluir todos os episódios relacionados a um filme, caso o filme seja excluido
    filme = models.ForeignKey("Filme", related_name="episodios", on_delete=models.CASCADE)
    titulo = models.CharField(max_length=140)
    video = models.URLField()

    def __str__(self):
        return self.filme.titulo + " - " + self.titulo


#Criando a classe padrão de usuários do django - Ela herda todas as características já existentes nele - Aqui só é preciso colocar o que queremos acrescentar.
class Usuario(AbstractUser):
    #Criando a relação "Muito p/ Muitos" entre as classes, Usuário e Filme.
    filmes_vistos = models.ManyToManyField("Filme")


#Para realmente criar o modelo de Usuário 4 passos precisam ser seguidos
#1°: Criar no Modelo de usuário no arquivo models.py do app
#2°: Registrar o Modelo no admin.py, com um parâmetro adicional, que é o UserAdmin - Que basicamente diz pro django qual classe vai gerenciar os usuários.
#3°: Passar o Modelo para settings.py, com a variável: AUTH_USER_MODEL = "nome_do_app.Usuario".
#4°: Adicionar os campos personalizados no fields do UserAdmin
#OBS: Sempre fazer isso no início da criação do site

filme/forms.py
#Classe de que tem como finalidade criar um usuario
from django.contrib.auth.forms import UserCreationForm
from .models import Usuario
from django import forms


#Formulário Padrão do Django
class FormHomePage(forms.Form):
    email = forms.EmailField(label=False)


#Sobre a class Meta: O Django vai criar um formulário, baseado nas configurações do meu modelo de usuário.
class FormCriarConta(UserCreationForm):
    email = forms.EmailField()  #required=False: Torna o campo como opicional

    class Meta:
        model = Usuario
        #fields: Define quais campos irão aparecer
        fields = ("username", "email", "password1", "password2")

filme/views.py
from django.shortcuts import redirect, reverse
from .models import Filme, Usuario
#TemplateView: Quando Objetivo é apenas renderizar uma página HTML na classe.
#ListView: Quando o Objetivo é exibir uma Lista de Itens do banco de dados.
from django.views.generic import TemplateView, ListView, DetailView, FormView, UpdateView
#Importação que será passada para a class base view, para bloquear aquela rota apenas para usuários autenticados.
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from .forms import FormCriarConta, FormHomePage
# Create your views here.

#template_name: Váriavel Padrão da Classe TemplateView do Django, usada para determinar a página HTML que vai ser renderizada.
class Homepage(FormView):
    template_name = "homepage.html"
    form_class = FormHomePage

    def get(self, request, *args, **kwargs):
        #Verifica se o usuário está autenticado
        #Caso ele estja autenticado eu vou redireciona-lo para a página de filmes
        if request.user.is_authenticated:
            return redirect("filme:homefilmes")
        #Caso contrário, continuar retornando a página html padrão que é a homepage
        else:
            return super().get(request, *args, **kwargs)

    #Pegando o email da requisição POST que o usuário está fazendo na página Home
    def get_success_url(self):
        email = self.request.POST.get("email")
        #Caso o email exista, retornar página de login
        usuario = Usuario.objects.filter(email=email).first()
        if usuario:
            return reverse("filme:login")
        #Caso nao exista retorna página de criar conta
        else:
            return reverse("filme:criarconta")

#Fax todoo o processo de criação de contexto automáticamente - Como foi feito na Functions Base Views Anteriormente
class HomeFilmes(LoginRequiredMixin, ListView):
    template_name = "homefilmes.html"
    #Cria uma lista da tabela "Filme" do banco de dados e retorna a variável "object_list" para página html em que está implementada.
    model = Filme #object_list -> Lista os itens do modelo

#Por padrão passar as mesmas variáveis que um ListView.
#DetailView: Cria um página para cada filme que existe no banco de dados - Exibindo os seus detalhes.

#Quando for necessário passar uma variável para dentro de umaview específica, é preciso alterar a variável:
#def get_context_data(self, **kwargs) - Que caso essa função vai possibilitar adicionar um valor na variável context
#context = super(DetalhesFilme, self).get_context_data(**kwargs) - Para não sobreescrever as funcionalidade dessa função da classe mas sim adicionar um valor nela.
class DetalhesFilme(LoginRequiredMixin, DetailView):
    template_name = "detalhesfilme.html"
    model = Filme #object -> 1 Item do modelo

    #Definindo a função get, onde vai ser criado a lógica de contabilizar as visualizações de cada filme.
    #O real motivo é contabilizar quantas vezes os usuários dão um click em uma página. Ou seja quando o usuário da um "get" na página
    #Parâmetro padrões: request, *args, **kwargs
    def get(self, request, *args, **kwargs):
        filme = self.get_object()
        filme.views += 1
        #Salva o valor que foi adicionado a coluna views
        filme.save()
        #Adicionar o filme que o usuário clicou para ver na lista de filmes_vistos do usuário atual
        user = request.user
        user.filmes_vistos.add(filme)
        return super().get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(DetalhesFilme, self).get_context_data(**kwargs)
        #Filtrar a tabela de filmes, cujo as categorias são iguais as categorias do filme da página
        #self.get_object() - Usado para pegar a variável object
        #[0:5] Para limitar a lista, ou seja, pegar primeiro item até o quinto item.
        filmes_relacionados = self.model.objects.filter(categoria=self.get_object().categoria)[0:5]
        context["filmes_relacionados"] = filmes_relacionados #A variável no HTML sempre será a chave do que foi definida
        return context


class Pesquisafilme(LoginRequiredMixin, ListView):
    template_name = "pesquisa.html"
    model = Filme

    #get_queryset: Serve para pegar os parâmetros da minha query/busca. E a partir disso, dizer quais informações seram passadas para o object_list.
    def get_queryset(self):
        query = self.request.GET.get("query")
        if query:
            #titulo__icontains: Vai verificar se o texto que foi passado como parâmetro, está contido no titulo. Ou essa verificação poderia ser feita por outra coluna da tabela, como a descrição, por exemplo.
            object_list = self.model.objects.filter(titulo__icontains=query)
            return object_list
        else:
            return None

#UpdateView: Classe utilizada para realizar uma atualização no banco de dados baseado no modelo que você passa.
#fields: Diz Quais campos do banco de dados o usuário vai poder atualizar
#UserPassesTestMixin: Previnir para que apenas o request_user, tenha autorização para alterar o prórpio perfil
class EditarPerfil(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    template_name = "editarperfil.html"
    model = Usuario
    fields = ["first_name", "last_name", "email"]

    #Retorna apenas o usuário que é o próprio usuário da requisição atual
    def test_func(self):
        user = self.get_object()
        return self.request.user == user

    def get_success_url(self):
        return reverse("filme:homefilmes")



class CriarConta(FormView):
    template_name = "criarconta.html"
    form_class = FormCriarConta

    #form_valid: Editando essa função para que o formulário seja salvo efitivamente no banco de dados
    def form_valid(self, form):
        form.save()
        return super().form_valid(form)

    #Retorna o usuário para uma determinada página, caso a criação de conta tenha sido feita com sucesso
    #reverse: Utilizar quando a função pede como resposta um texto de link, ele pega o link correspondente ao html que foi pasasdo como parâmetro
    def get_success_url(self):
        return reverse("filme:login")

filme/templates/detalhesfilme.html
{% extends "base.html" %}

{% block titulo %}
HomeFilmes HashFlix
{% endblock %}

{% block content %}
    <main class='bg-primary_black min-h-screen w-full'>
        <section class="h-screen relative bg-no-repeat pb-8 pl-6 flex  items-end bg-cover" style="background-image: url('{{ object.thumb.url }}');">
            <div>
                <h2 class="text-6xl font-semibold text-white my-4">
                    {{ object.titulo }}
                </h2>
                <p class=" w-11/12 md:w-5/12 font-medium text-white my-4">
                    {{ object.descricao|slice:"0:50" }}... <!--Edita/Limita o texto em um máximo de caracteres-->
                </p>
                <div class="flex my-4">
                    <a href="{{ object.episodios.first.video }}">
                        <button class="flex items-center bg-white py-2 px-5 rounded-md" style='color:black;'>
                            <ion-icon name="play" class="text-2xl"></ion-icon>
                            <span class="ml-3 font-medium">
                                Play
                            </span>
                        </button>
                    </a>
                </div>
            </div>
        </section>
        <section class='bg-primary_black flex justify-center py-10'>
            <div class="p-8 w-10/12 relative" >
                <h2 class="text-gray-200 text-3xl font-medium">
                    Descrição
                </h2>
                <div class="flex justify-left  items-center min-w-full  movie_lis">
                    <p class="text-gray-100 text-lg">
                        {{ object.descricao }}<br>
                        Visualizações: {{ object.views }}
                    </p>
                </div>
                <div style='margin-top:2rem;margin-bottom:2rem;'>
                    <h2 class="text-gray-200 text-3xl font-medium">
                        Episódios
                    </h2>
                    {% for episodio in object.episodios.all %}
                      <h3 class='text-lg'>
                          <a href="{{ episodio.video }}">
                          Episódio {{ forloop.counter }}: {{ episodio.titulo }}
                          </a>
                      </h3>
                    {% endfor %}
                </div>
            </div>
        </section>

        <section class='bg-primary_black flex justify-center py-10'>
            <div class="p-8 w-10/12 relative" >
                <h2 class="text-gray-200 text-2xl font-medium">
                    Relacionados
                </h2>
                <div class="flex flex-wrap items-center min-w-full movie_lis">
                   {% for filme in filmes_relacionados %}
                    <div class="m-4 bg-blue-500 overflow-hidden flex-shrink-0 rounded-md cursor-pointer h-64 w-96">
                        <a href="{% url 'filme:detalhesfilme' filme.pk %}">
                          <img src="{{ filme.thumb.url }}" class="object-cover w-full h-full " alt="">
                        </a>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </section>
    </main>
{% endblock %}

filme/templates/editarperfil.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block titulo %}
Editar Perfil - HashFlix
{% endblock %}

{% block content %}
<header class="min-h-screen bg-black bg-opacity-75 bg-blend-overlay showcase border-gray-600 border-b-8 flex justify-center items-center bg-no-repeat"  style="background-image: url('{% static 'images/background_netflix.jpg' %}');">
        <div class="z-10 h-full py-32 md:py-0 text-gray-100 text-center flex items-center flex-col">
            <form method="post">
                {% csrf_token %}
                <h2 class="text 2xl">{{ request.user.email }}</h2>
                <fieldset class="form-group">
                    <legend class="border-bottom mb-4">Edite os campos abaixo.</legend>
                    {{ form|crispy }}
                </fieldset>
                <button class="bg-red-600 py-1 my-2 px-3 w-full text-white md:text-lg rounded-md" type="submit">Confirmar Edição</button>
            </form>
            <small><a href="{% url 'filme:mudarsenha' %}">Também deseja mudar sua senha? Clique aqui.</a></small>
        </div>
    </header>
    <footer class=" px-5 py-10 ">
        <ul class="flex justify-between items-center">

            <li>&copy; 2021</li>
            <li> Feito com Python (Django)</li>
            <li>Hashtag</li>
        </ul>
    </footer>
{% endblock %}

filme/templates/homefilmes.html
{% extends "base.html" %}

{% block titulo %}
    HomePage HashFlix
{% endblock%}

{% block head %}
<style>
$itemGrow: 1.2;
$duration: 250ms;

html {
scroll-behavior: smooth;
}

body {
margin: 0;
background-color: #000;
}

h1 {
font-family: Arial;
color: red;
text-align: center;
}

.wrapper {
display: grid;
grid-template-columns: repeat(3,100%);
overflow:hidden;
scroll-behavior: smooth;

section {
  width: 100%;
  position: relative;
  margin: 20px 0;

  .item {
    padding: 0 2px;
    transition: $duration all;

    &:hover {
      margin: 0 40px;
      transform: scale(1.2);
    }

  }

  a {
    /* position: absolute; */
    color: #fff;
    text-decoration: none;
    font-size: 6em;
    background:rgb(0,0,0);
    text-align: center;
    z-index: 1;

  }

  &>a:first-child {
    position: absolute;
      left:0;
      background: linear-gradient(-90deg, rgba(0,0,0,0) 0%, rgba(0,0,0,1) 100%);
    }
    &>a:last-child {
      position: absolute;
      right: 0;
      background: linear-gradient(90deg, rgba(0,0,0,0) 0%, rgba(0,0,0,1) 100%);
    }
}
}

// Remove the arrow for Mobile
@media only screen and (max-width: 600px) {
a.arrow__btn {
  display:none;
}
}
</style>
{% endblock %}

{% block content %}
    <main class='bg-primary_black min-h-screen w-full'>
        <section class="h-screen relative bg-no-repeat pb-8 pl-6 flex items-end bg-cover" style="background-image: url('{{ lista_filmes_recentes.first.thumb.url }}');">
            <div>
                <h2 class="text-6xl font-semibold text-white my-4">
                    {{ lista_filmes_recentes.first.titulo }}
                </h2>
                <p class=" w-11/12 md:w-5/12 font-medium text-white my-4">
                    {{ lista_filmes_recentes.first.descricao|slice:"0:50" }}...
                </p>
                <div class="flex my-4">
                    <a href="{% url 'filme:detalhesfilme' lista_filmes_recentes.first.pk %}">
                        <button class="flex items-center bg-white py-2 px-5 rounded-md" style='color:black;'>
                            <ion-icon name="play" class="text-2xl"></ion-icon>
                            <span class="ml-3 font-medium ">
                                Play
                            </span>
                        </button>
                    </a>
                </div>
            </div>
        </section>

        <section class='bg-primary_black flex justify-center py-10 z-60'>
            <div class="p-8 w-10/12 relative" >
                <h2 class="text-gray-200 text-2xl font-medium">
                    Novo
                </h2>
                <div class="wrapper">
                  <section id="section1" class="flex flex-nowrap items-center justify-center space-x-8">
                      <a href="#section2" class="arrow__btn text-6xl page">‹</a>
                      {% for filme in lista_filmes_recentes %}
                      {% if forloop.counter < 5 %}
                      <div class="item h-64 w-1/4 m-4">
                          <a href="{% url 'filme:detalhesfilme' filme.pk %}">
                            <img src="{{ filme.thumb.url }}" class="rounded-md w-full h-full object-cover">
                          </a>
                      </div>
                      {% endif %}
                      {% endfor %}
                      <a href="#section2" class="arrow__btn text-6xl">›</a>
                  </section>
                    {% if lista_filmes_recentes|length > 4 %}
                      <section id="section2" class="flex flex-nowrap items-center justify-center">
                        <a href="#section1" class="arrow__btn text-6xl">‹</a>
                          {% for filme in lista_filmes_recentes %}
                          {% if forloop.counter > 4 %}
                          <div class="item h-64 w-1/4 m-4">
                              <a href="{% url 'filme:detalhesfilme' filme.pk %}">
                                <img src="{{ filme.thumb.url }}" class="rounded-md w-full h-full object-cover">
                              </a>
                          </div>
                          {% endif %}
                          {% endfor %}
                        <a href="#section1" class="arrow__btn text-6xl">›</a>
                      </section>
                    {% endif %}
                </div>
            </div>
        </section>

        <section class='bg-primary_black flex justify-center py-10'>
            <div class="p-8 w-10/12 relative" >
                <h2 class="text-gray-200 text-2xl font-medium">
                    Em Alta
                </h2>
                <div class="wrapper">
                  <section id="section1emalta" class="flex flex-nowrap items-center justify-center space-x-8">
                    <a href="#section2emalta" class="arrow__btn text-6xl page">‹</a>
                      {% for filme in lista_filmes_alta %}
                      {% if forloop.counter < 5 %}
                      <div class="item h-64 w-1/4 m-4">
                          <a href="{% url 'filme:detalhesfilme' filme.pk %}">
                            <img src="{{ filme.thumb.url }}" class="rounded-md w-full h-full object-cover">
                          </a>
                      </div>
                      {% endif %}
                      {% endfor %}
                        <a href="#section2emalta" class="arrow__btn text-6xl">›</a>
                  </section>
                    {% if lista_filmes_alta|length > 4 %}
                      <section id="section2emalta" class="flex flex-nowrap items-center justify-center">
                        <a href="#section1emalta" class="arrow__btn text-6xl">‹</a>
                          {% for filme in lista_filmes_alta %}
                          {% if forloop.counter > 4 %}
                          <div class="item h-64 w-1/4 m-4">
                              <a href="{% url 'filme:detalhesfilme' filme.pk %}">
                                <img src="{{ filme.thumb.url }}" class="rounded-md w-full h-full object-cover">
                              </a>
                          </div>
                          {% endif %}
                          {% endfor %}
                        <a href="#section1emalta" class="arrow__btn text-6xl">›</a>
                      </section>
                    {% endif %}
                </div>
            </div>
        </section>

        {% if request.user.filmes_vistos.all %}
        <section class='bg-primary_black flex justify-center py-10'>
            <div class="p-8 w-10/12 relative" >
                <h2 class="text-gray-200 text-2xl font-medium">
                    Continuar Assistindo
                </h2>
                <div class="wrapper">
                  <section id="sectionvistos1" class="flex flex-nowrap items-center justify-center space-x-8">
                    <a href="#sectionvistos2" class="arrow__btn text-6xl page">‹</a>
                      {% for filme in request.user.filmes_vistos.all %}
                      {% if forloop.counter < 5 %}
                      <div class="item h-64 w-1/4 m-4">
                          <a href="{% url 'filme:detalhesfilme' filme.pk %}">
                            <img src="{{ filme.thumb.url }}" class="rounded-md w-full h-full object-cover">
                          </a>
                      </div>
                      {% endif %}
                      {% endfor %}
                        <a href="#sectionvistos2" class="arrow__btn text-6xl mx-2">›</a>
                  </section>
                    {% if request.user.filmes_vistos.all|length > 4 %}
                      <section id="sectionvistos2" class="flex flex-nowrap items-center justify-center">
                        <a href="#sectionvistos1" class="arrow__btn text-6xl">‹</a>
                          {% for filme in request.user.filmes_vistos.all %}
                          {% if forloop.counter > 4 %}
                          <div class="item h-64 w-1/4 m-4">
                              <a href="{% url 'filme:detalhesfilme' filme.pk %}">
                                <img src="{{ filme.thumb.url }}" class="rounded-md w-full h-full object-cover">
                              </a>
                          </div>
                          {% endif %}
                          {% endfor %}
                        <a href="#sectionvistos1" class="arrow__btn text-6xl">›</a>
                      </section>
                    {% endif %}
                </div>
            </div>
        </section>
        {% endif %}
    </main>
{% endblock %}

filme/templates/homepage.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block titulo %}
    HomePage HashFlix
{% endblock %}

{% block head %}
<style>
    #id_email{
    width: 310px; /* Defina o tamanho desejado */
    padding: 12px;
    font-size: 1rem;
    border: none;
    border-radius: 0.25rem 0 0 0.25rem; /* Para combinar com o botão */
    box-sizing: border-box;
    color: #000000;
}
</style>
{% endblock %}

{% block content %}
    {% block navbar %}
    {% include "navbarlogout.html" %}
    {% endblock %}
     <header class="min-h-screen bg-black bg-opacity-75 bg-blend-overlay showcase border-gray-600 border-b-8 flex justify-center items-center bg-no-repeat"  style="background-image: url('{% static 'images/background_netflix.jpg' %}');">
        <div class="z-10 h-full py-32 md:py-0 text-gray-100 text-center flex items-center flex-col">

            <h1 class="font-semibold text-4xl md:text-5xl w-10/12 md:w-3/4 text-center">
                Filmes e séries da Hashtag, tudo em um só lugar.
            </h1>
            <h3 class="text-xl md:text-xl py-5">
                Assista onde quiser. Cancele quando quiser.
            </h3>
            <h4 class="text-sm md:text-lg pb-3">
                Quer começar? Coloque seu e-mail abaixo para acessar.
            </h4>
            <h5 class="text-sm md:text-lg pb-3">
                Não tem uma conta? <a href="{% url 'filme:criarconta' %}">Clique aqui para criar uma conta.</a>
            </h5>

            <div class="w-full flex justify-center">
                <div class="flex justify-center items-center w-11/12 md:w-10/12">
                    <form method="post" class="w-6/12 justify-center">
                        {% csrf_token %}
                        <div class="flex flex-grow items-stretch">
                            {{ form }}
                            <button class="bg-red-600 font-medium md:font-normal flex justify-center items-center py-2 px-3 md:px-0 rounded-br-sm rounded-tr-sm md:text-2xl" type="submit">
                                <span>
                                    Acessar
                                </span>
                                <ion-icon name="chevron-forward-outline" class="text-2xl"></ion-icon>
                            </button>
                        </div>
                    </form>
                </div>
            </div>

        </div>
    </header>

    <section class='flex flex-col md:flex-row items-center border-gray-900 border-b-8' style="min-height: 70vh;">
        <div class="md:w-1/2 flex flex-col justify-center text-center md:text-left p-5 md:p-10 ">
            <h2 class="md:text-5xl text-4xl font-semibold mb-4">
                Enjoy on your TV.
            </h2>
            <h5 class="md:text-xl text-lg">
                Watch on Smart TVs, Playstation, Xbox, Chromecast, Apple TV, Blu-ray players, and more.
            </h5>
        </div>
        <div class='md:w-1/2 flex justify-center items-center'>
            <img src="{% static 'images/tv.png' %}" class="w-8/12" alt="">
        </div>
    </section>

    <section class='flex flex-col md:flex-row items-center border-gray-900 border-b-8' style="min-height: 70vh;">
        <div class='md:w-1/2 flex justify-center items-center '>
            <img src="{% static 'images/mobile-0819.jpg' %}" class="w-8/12" alt="">
        </div>

        <div class="md:w-1/2 flex flex-col justify-center text-center md:text-left p-5 md:p-10">
            <h2 class="md:text-5xl text-4xl font-semibold mb-4">
                Download your shows to watch offline.
            </h2>
            <h5 class="md:text-xl text-lg">
                Save your favorites easily and always have something to watch.
            </h5>
        </div>
    </section>

    <section class='flex flex-col md:flex-row items-center border-gray-900 border-b-8' style="min-height: 70vh;">
        <div class="md:w-1/2 flex flex-col justify-center text-center md:text-left p-5 md:p-10">
            <h2 class="md:text-5xl text-4xl font-semibold mb-4">
                Create profiles for kids.
            </h2>
            <h5 class="md:text-xl text-lg">
                Send kids on adventures with their favorite characters in a space made just for them—free with your membership.
            </h5>
        </div>
        <div class='md:w-1/2 flex justify-center items-center'>
            <img src="{% static 'images/netflix_kid.png' %}" class="w-8/12" alt="">
        </div>
    </section>
    <footer class=" px-5 py-10 ">
        <ul class="flex justify-between items-center">

            <li>&copy; 2024</li>
            <li> Feito com Python (Django)</li>
            <li>Hashtag</li>
        </ul>
    </footer>
{% endblock %}