cursosflix/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

#namespace é usado para agrupar URLs sob um prefixo comum, o que é útil para evitar conflitos de nome quando você tem várias aplicações que podem ter rotas com nomes iguais.
#Basicamente ele identifica o arquivo url.py do app exato que ele precisa pegar, cujo a variável "app_name" possui o mesmo nome que foi passado como parâmetro para a variável "namespace"
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('filme.urls', namespace='filme')),
]
#urls para os arquivos estáticos
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
#urls para os arquivos de mídia
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

filme/urls.py
# url - view - template
from django.urls import path, reverse_lazy
#reverse_lazy: Passado pro path para retornar o link da página que o usuário vai entrar ao submeter o formulário
from .views import HomeFilmes, Homepage, DetalhesFilme, Pesquisafilme, EditarPerfil, CriarConta
#Importação para pegar a classe de Login que já vem pronta do Django
from django.contrib.auth import views as auth_view

#app_name é usada dentro dos arquivos urls.py de um aplicativo para definir um namespace próprio para esse conjunto de URLs.
app_name = "filme"

#Para Functions Base Views: Passar o nome da função como parâmetro o Django já vai entender que queremos renderizar a página HTML que está definida na função
#Para Class Base Views: Necessário passar NomeDaClasse.as_view() - "()" É obrigatório passar.

#A criação do link de página que renderiza uma DetailView é diferente:
#Ele espera que tenha um parâmetro na url dentro de "< >" - E também precisa informar o tipo desse parâmetro. Ex: int, float, str...
#No exemplo foi utilizado "int:pk" onde "pk" é a primary key da tabela que foi implementada na DetailView
#Ele faz essa busca automaticamente - Tendo em mente que foi definida a tabela do banco de dados que vamos renderizar
urlpatterns = [
    path('', Homepage.as_view(), name="homepage"),
    path('filmes/', HomeFilmes.as_view(), name="homefilmes"),
    path('filmes/<int:pk>', DetalhesFilme.as_view(), name="detalhesfilme"),
    path('pesquisa/', Pesquisafilme.as_view(), name="pesquisafilme"),
    #template_name: Para o Django diferenciar os HTML's das views que possuem a classe pronta do Django.
    path('login/', auth_view.LoginView.as_view(template_name="login.html"), name="login"),
    path('logout/', auth_view.LogoutView.as_view(template_name="logout.html"), name="logout"),
    path('editar-perfil/<int:pk>', EditarPerfil.as_view(), name="editarperfil"),
    path('criar-conta/', CriarConta.as_view(), name="criarconta"),
    path('alterar-senha/', auth_view.PasswordChangeView.as_view(template_name="editarperfil.html",
                                                                success_url=reverse_lazy('filme:homefilmes')), name="mudarsenha")
]

#o parâmetro name usado nas rotas (URLs) serve para dar um nome único a cada rota, permitindo que você se refira a essas rotas d    e uma maneira mais fácil e robusta em todo o seu código.

templates/base.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <title>
        {% block titulo %}
        {% endblock %}
    </title>
    <script src="https://cdn.tailwindcss.com"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    {% block head %}
    {% endblock %}
</head>
<body class="bg-black text-gray-100 font-primary">
    {% block navbar %}
    {% include "navbar.html" %}
    {% endblock %}

    {% block content %}
    {% endblock %}
    <script type="module" src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js"></script>
    <script>
        const nav = document.querySelector('nav')

        document.addEventListener("scroll",e=>{
            if(scrollY>100){
                if(scrollY>window.innerHeight){
                nav.classList.add('invisible')
            }else{
                nav.classList.add('bg-gray-900')
                nav.classList.remove('invisible')
            }
            }else{
                nav.classList.remove('bg-gray-900')
                nav.classList.remove('invisible')
            }
        })
    </script>
</body>
</html>

templates/navbar.html
<!-- Descrevendo as classes do Tailwindcss
 w-full: A barra de navegação vai ter a largura da página inteira
 flex: Utilitário para controlar como os items vão se comportar dentro da barra de navegação
 justify-between: Ajustar/Destribuir a distânca dos objetos de onde está implementado de forma dinâmica
 items-center: Items centralizados verticalmente
 fixed: Fixar uma informação no topo da tela o tempo inteiro, que no caso é a barra de navegação
 z-50: As coisas que estão com z abaixo de 50 vão estar atrás da barra de navegação se z estiver acima vai ocorrer o sentido contrário.-->
{% load static %}
<nav class="w-full flex justify-between items-center py-3 px-4 fixed z-50">
    <!--w-6/12: pega metade da largura de elemento, ou seja a barra de navegação-->
    <div class="w-6/12">
        <a href="{% url 'filme:homepage' %}">
            <img src="{% static 'images/hashflix.png' %}">
        </a>
    </div>
    <div class="w-6/12 flex flex-nowrap justify-end">
        <!--mr-2: Adicona margem a direita
        rounded-md: Coloca bordas redondas no formulário
        text-black: Define o texto de fundo para cor preta
        flex-nowrap: Garante que os elementos vão estar um do lado do outro
        justify-end: Alinhar os elementos à direita
        action: Ação que o formulário vai fazer, ou seja, qual link vai redicerionar-->
        {% if user.is_authenticated %}
        <div class="mr-2">
            <form method="get" action="{% url 'filme:pesquisafilme' %}">
                <!--As configurações de input abaixo, fazem o input passar o parâmetro que está na barra de pesquisa para url
                value="{{ request.GET.query }}: Mantém dentro do input a pesquisa do usuário "-->
                <input type="text" class="py-1 px-2 rounded-md text-black" name="query" value="{{ request.GET.query }}" placeholder="Pesquisar...">
                <input type="submit" value="">
            </form>
        </div>
        {% endif %}
        <div class="mr-2">
            {% if user.is_authenticated %}
            <form id="logout-form" method="post" action="{% url 'filme:logout' %}">
                {% csrf_token %}
                <button class="bg-red-600 py-1 px-3 text-white rounded-md" type="submit">Sair</button>
            </form>
            {% else %}
            <a href="{% url 'filme:login' %}">
                <button class="bg-red-600 py-1 px-3 text-white rounded-md">Login</button>
            </a>
            {% endif %}
        </div>
        {% if user.is_authenticated %}
        <div class="mr-2">
            <a href="{% url 'filme:editarperfil' request.user.pk %}">
                <button class="bg-red-600 py-1 px-3 text-white rounded-md">
                    Editar Perfil
                </button>
            </a>
        </div>
        {% endif %}
    </div>
</nav>

templates/navbarlogout.html
<!-- Descrevendo as classes do Tailwindcss
 w-full: A barra de navegação vai ter a largura da página inteira
 flex: Utilitário para controlar como os items vão se comportar dentro da barra de navegação
 justify-between: Ajustar/Destribuir a distânca dos objetos de onde está implementado de forma dinâmica
 items-center: Items centralizados verticalmente
 fixed: Fixar uma informação no topo da tela o tempo inteiro, que no caso é a barra de navegação
 z-50: As coisas que estão com z abaixo de 50 vão estar atrás da barra de navegação se z estiver acima vai ocorrer o sentido contrário.-->
{% load static %}
<nav class="w-full flex justify-between items-center py-3 px-4 fixed z-50">
    <!--w-6/12: pega metade da largura de elemento, ou seja a barra de navegação-->
    <div class="w-6/12">
        <a href="{% url 'filme:homepage' %}">
            <img src="{% static 'images/hashflix.png' %}">
        </a>
    </div>
</nav>